[package]
name = "sphinx-packet"
version = "0.7.0"
authors = ["Ania Piotrowska <ania@nymtech.net>", "Dave Hrycyszyn <futurechimp@users.noreply.github.com>", "Jędrzej Stuczyński <andrew@nymtech.net>"]
edition = "2021"
license = "Apache-2.0"
description = "A Sphinx packet implementation in Rust"
repository = "https://github.com/nymtech/sphinx"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.9.1"
ctr = "0.10.1"
bs58 = "0.5.1"
x25519-dalek = { version = "3.0.0", features = ["static_secrets", "getrandom", "zeroize"] }

hmac = "0.13.0"
digest = "0.11.3"
rand = { version = "0.10.2", features = ["thread_rng"] }
rand_distr = "0.6.0"
sha2 = "0.11.0"
hkdf = "0.13.0"

lioness-rs = "0.2.0"
chacha20 = "0.10.1"
blake2 = "0.11.0-rc.6"

arrayref = "0.3.7"
byteorder = "1.5.0"
subtle = "2.4.1"
zeroize = { version = "1.7.0", features = ["zeroize_derive"] }

[dev-dependencies]
criterion = "0.8.2"
rand_chacha = "0.10.0"
lioness = "0.1.2"
blake2_08 = { package = "blake2", version = "0.8.0" }
chacha_03 = { package = "chacha", version = "0.3.0" }

[[bench]]
name = "benchmarks"
harness = false

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
todo = "deny"
dbg_macro = "deny"
exit = "deny"
panic = "deny"
unimplemented = "deny"
unreachable = "deny"
